# These are supported funding model platforms

github: [yuhr] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
liberapay: yuhr # Replace with a single Liberapay username
custom: ['https://www.buymeacoffee.com/yuhr'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
